spring.application.name=tcm-ai-backend
# ?? Spring Boot ???????
spring.datasource.url=jdbc:mysql://localhost:3306/tcm_ai?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=123456

# ??????????? SQL ??
spring.jpa.show-sql=true